apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: qho2bez5m-java-springboot
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-d9adfbc7b1.ywjl.p3.openshiftapps.com/rhtap/rhtap-qe:1f8fedc61ca13b54be5fd37e94570b5ded82ab01@sha256:de1e836ccc1a7cc3d39e33d27dea753efefd8ab3f5574630bb0e363b67b13e7e
          name: container-image
